In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import *

In [2]:
df = pd.read_csv('data/data_v5.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,Year,t1_general_traditional_WIN%,t1_general_traditional_PTS,t1_general_traditional_FGM,t1_general_traditional_FG%,t1_general_traditional_3PM,t1_general_traditional_3P%,t1_general_traditional_FTM,...,t2_clutch-opponent_Opponent's Steals,t2_clutch-opponent_Opponent's Blocks,t2_clutch-opponent_Opponent's Blocked Field Goal Attempts,t2_clutch-opponent_Opponent's Personal Fouls,t2_clutch-opponent_Opponent's Personal Fouls Drawn,t2_clutch-opponent_Opponent's Points,t2_TEAM,t2_seed,t2_series_wins,outcome
0,0,0,2001,56.1,91.9,34.1,43.1,4.1,34.6,19.5,...,0.6,0.5,0.3,2.7,2.1,7.4,Miami Heat,3,0,1
1,1,1,2001,63.4,100.7,38.0,45.8,6.9,37.9,18.0,...,0.6,0.4,0.5,2.5,3.1,8.8,Orlando Magic,7,1,1
2,2,2,2001,50.0,92.6,34.5,44.0,4.8,34.2,18.8,...,0.6,0.5,0.6,3.3,2.5,8.2,Philadelphia 76ers,1,3,0
3,3,3,2001,58.5,88.7,33.6,44.4,4.8,35.1,16.8,...,0.5,0.4,0.4,2.2,2.6,7.6,Toronto Raptors,5,3,0
4,4,4,2001,64.6,100.5,37.6,45.9,6.3,38.1,18.9,...,0.5,0.2,0.3,2.9,2.2,6.9,Utah Jazz,4,2,1

In [3]:
df.drop(columns=['Unnamed: 0.1','Unnamed: 0','Year','t1_TEAM','t2_TEAM'],inplace=True)

In [5]:
X = df.drop(columns=['outcome']).to_numpy()
y = df['outcome'].to_numpy()
mi = mutual_info_classif(X,y)

In [6]:
k_best = SelectKBest(mutual_info_classif,k=25).fit(X,y)

In [ ]:
k_best

In [7]:
selected_fts = k_best.get_feature_names_out(list(df.columns).remove('outcome'))

In [8]:
fts_list = []
for s in selected_fts:
    fts_list.append(int(s[1:]))

In [ ]:
subset_df = df.iloc[:,fts_list]

In [ ]:
subset_df['outcome']=y

In [ ]:
subset_df.head()

In [ ]:
subset_df.to_csv('data/data_v6_k25.csv')